# name: build

# on:
#   push:
#     branches: dev

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
  
#     steps:
#     - name: Checkout repo
#     - uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: 16

#     - name: Install dependencies
#       run: bahmutov/npm-install@v1

#     - name: Build project
#       run: npm run build

#     - name: Upload production-ready build files
#       uses: actions/upload-artifact@v4
#       with:
#         name: production-files
#         path: ./dist
  
#   deploy:
#     name: Deploying APP
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/dev'
    
#     steps:
#     - name: Download artifact
#     - uses: actions/checkout@v2

#     - name: Download Built Files for Node 14.x
#       uses: actions/download-artifact@v4
#       with:
#         name: built-files-14.x-${{ github.run_id }}
#         path: ./dist

#     - name: Deploy to GitHub Pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./dist

name: Build and Deploy

on:
  push:
    branches: dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
     
    - run: bahmutov/npm-install@v1

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: ./dist
  
  deploy:
    name: Deploying APP
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Built Files
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
